site_name: SMTR -  Pipelines
site_url: https://rj-smtr.github.io/pipelines-docs/

nav:
  - Home: index.md # descrição das pessoas, repositórios, da documentação
  - Quick Start: quick_start.md # setar ambiente virtual, instalar com poetry, mencionar o infisical, configuração por OS 
  - Pastas e arquivos: pastas_arquivos.md # descrição da estrutura de pastas e arquivos
  - Ambientes: ambientes.md # descrever ambientes de produção, staging e dev
  - Tabelas:
    - Manual de Estilo: tabelas/manual_estilo_tabelas.md # manual para criação de tabelas e modelos
    - Backup: tabelas/backups.md #descreve o processo de backups
  - Pipelines: 
    - Introdução: pipelines/introducao.md # descrição dos motivos para criarmos as pipelines como fazemos atualmente
    - Pipelines genéricos: pipelines/templates.md # templates de pipelines genéricos, captura, tratamento
    - Listagem das pipelines: # histórico das pipelines já existentes, para cada uma falar dos parâmetros e do que se trata    
      - Monitoramento: 
        - Apuração de viagens (SPPO) [1.0]: pipelines/listagem_pipelines/monitoramento/apuracao_viagens_v1.md # pipeline de apuração de viagens v1
      - FAQ: pipelines/listagem_pipelines/faq.md # perguntas frequentes sobre as pipelines de apuração do subsídio
  - Datasets: datasets.md # histórico dos datasets já existentes
  - Ferramentas: ferramentas.md # ferramentas e versões utilizadas

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/lightbulb
        name: Mudar para tema escuro
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Mudar para tema claro

  logo: img/logo_branco.png

  favicon: img/favicon.ico

  font:
      text: Gotham
  features: 
        - navigation.top
  language: pt

extra:
   social:
   - icon: fontawesome/brands/github
     link: https://github.com/prefeitura-rio/pipelines_rj_smtr

extra_css:
- static/extra.css
